<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib uri="/WEB-INF/bridgei2i.tld" prefix="bi2itag"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Map"%>
<%@page import="com.bridgei2i.common.util.ApplicationUtil"%>
<%@page import="com.bridgei2i.common.constants.ApplicationConstants"%>
<%@page import="com.bridgei2i.common.vo.Users"%>
<%
	String contextPath = request.getContextPath();
%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>BRIDGEi2i | Terms Of Use</title>
</head>
<body style="margin-top: 0px;">
<form:form method="post" action="terms-of-use.htm"
		commandName="model" name="termsOfUse">

<div class="tabbable tabs-left" style="padding: 0px 10px;">
		<div style="width: 250px; position: fixed; margin-top: 40%;">
		
			<table style="height: 100%; margin-left: 10%">
				<tr>
					<td valign="middle"
						style="font-size: 6; color: #A9A9A9;">Powered
						by: <br> <a href="http://www.bridgei2i.com" target="_blank">
						<img
						src="<%=contextPath%>/images/bi2i-logo-trans.png" width="60%"
						height="50%" /></a>
					</td>
				</tr>
			</table>
		</div>
		<div class="tab-content"
			style="position: relative; width: 86%; float: right;">

				<div id="page-wrapper"	style=" overflow-x: auto; margin-left: 4px;margin-right: -18px;min-height: 658px;border: 1.9px solid #ddd;margin-bottom:-11px;">
					
					<div class="row" style="text-align: left;line-height: 19px;font-size: 14px;margin-top:75px;padding-left: 15px; ">

<p style="text-align:center;font-family: Segoe UI !important;font-size: 35px;padding-bottom: 26px;">TERMS OF SERVICE</p>

<p style="text-align:justify;  padding-right: 15px;">Effective starting: July 8, 2015 <br><br>

These terms of service ("Terms of Service") apply exclusively to your access to, use of and registration for the services and products available on the <a href="http://localhost:8080/SKUPlanningTool/login.jsp" target="_blank">HP SKU Planner</a> and allied hosting platforms (together "the Website") owned and operated by BRIDGEi2i Analytics Solutions Private Limited.<br><br>

BRIDGEi2i Analytics Solutions Private Limited Customer Agreement (the "<b>Agreement</b>") is between HP Contracting Entity ("HP") users and BRIDGEi2i Analytics Solutions Private Limited, a company incorporated under the Companies Act, 1956 with its Registered Office at Umiya Business Bay, Tower 1, 2nd Floor Cessna Business Park, Village, Vartur Hobli, Outer Ring Rd, Kadubeesanahalli, Bengaluru, Karnataka 560037. If you are agreeing to this Agreement not as an individual but on behalf of your company, then "<b>Customer</b>" or "<b>you</b>" means your company, and you are binding your company to this Agreement.<br><br>

These Terms of Service do not alter in any way the terms or conditions of any other agreement you may have with BRIDGEi2i, or its subsidiaries or affiliates, for Services or otherwise. If you are using the Website on behalf of any entity, you represent and warrant that you are authorized to accept these Website Terms of Service on such entity's behalf, and that such entity agrees to indemnify BRIDGEi2i for violation of these Terms of Service.<br>&nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Scope of the Agreement </p>

<p style="text-align:justify;  padding-right: 15px;">This Agreement governs your initial purchase as well as any future purchases made by you that reference this Agreement. This Agreement includes our Privacy Policy, our Acceptable Use Policy, any Orders, and any other referenced policies and attachments. <br> &nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Types of BRIDGEi2i Analytics Solutions Private Limited Products </p>
<p style="text-align:justify;  padding-right: 15px;">This Agreement governs (a) BRIDGEi2i's commercially available downloadable software products (currently designated as "Server" or "Data Centre" deployments) ("<b>Software</b>"), (b) BRIDGEi2i's hosted or cloud-based solutions (currently designated as "Cloud" deployments) ("<b>Hosted Services</b>"), and (c) any related support or maintenance services provided by BRIDGEi2i. Software and Hosted Services, together with related Documentation, are referred to as "<b>Products</b>". The Products and their permitted use are further described in BRIDGEi2i's standard documentation ("<b>Documentation</b>"). Section 6 (Software Terms) applies specifically to Software, and Section 7 (Hosted Services Terms) applies specifically to Hosted Services, but unless otherwise specified, other provisions of this Agreement apply to all Products. <br> &nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Account Registration </p>
<p style="text-align:justify;  padding-right: 15px;">You may need to register for a HP SKU Planning Tool account in order to place orders or access the HP SKU Planner or receive any updates. Any registration information that you provide to us must be accurate, current and complete. You must also update your information so that we may send notices, statements and other information to you by email or through your account. You are responsible for all actions taken through your accounts. You are solely responsible for any use and all activities that occur under your account. You are responsible for safeguarding the confidentiality of your password(s) and user name(s) and for any use or misuse of your account resulting from any third party using a password or user name. You agree to notify BRIDGEi2i immediately of any unauthorized use of your account or any other breach of security.<br><br>

If you allow a third party access to the Services through your account, you shall inform BRIDGEi2i and you shall ensure that said third party is bound by and abides by the terms of this Agreement. All provisions in this Agreement are applicable to the third party.<br><br>
BRIDGEi2i and HP Contracting Entity ("HP") are its discretion in determining whether to accept a member to use our Services related to HP SKU Planner and may refuse membership to the HP SKU Planner and use of the Services to anyone without the need to provide explanation.<br><br>
From time to time, BRIDGEi2i may find it necessary to access your account. For instance, BRIDGEi2i may use admin access to your account for support, maintenance or security-related reasons. <br><br>
Please refer to our Privacy Policy to know more about our policy with regards to collection, storage and use of personally identifiable information provided by you.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Orders </p>

<p style="text-align:justify;  padding-right: 15px;"><strong>Directly with BRIDGEi2i </strong><br>
BRIDGEi2i's Product ordering documentation or purchase flow ("Order") will specify your authorized scope of use for the Products, which may include: (a) number and type of Authorized Users (as defined below), (b) storage or capacity (for Hosted Services), (c) numbers of licenses, copies or instances (for Software), or (d) other restrictions or billable units (as applicable, the "<b>Scope of Use</b>"). The term "<b>Order</b>" also includes any applicable Product or Support and Maintenance renewal, or purchases you make to increase or upgrade your Scope of Use.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Authorized Users </p>
<p style="text-align:justify;  padding-right: 15px;">Only the specific individuals whom you designate through the applicable HP SKU Planner product ("<b>Authorized Users</b>") may access and use the HP SKU Planner. Authorized Users may be your or your Affiliates' employees, representatives, consultants, contractors, agents, or other third parties who are acting for your benefit or on your behalf. You may increase the number of Authorized Users permitted to access your instance of the Product by placing a new Order or, in some cases, directly through the Product. In all cases, you must pay the applicable fee for the increased number of Authorized Users. You are responsible for compliance with this Agreement by all Authorized Users. All use of HP SKU Planner by you and your Authorized Users must be within the Scope of Use and solely for the benefit of you or your Affiliates. "<b>Affiliate</b>" means an entity which, directly or indirectly, owns or controls, is owned or is controlled by or is under common ownership or control with a party, where "control" means the power to direct the management or affairs of an entity, and "ownership" means the beneficial ownership of 50% (or, if the applicable jurisdiction does not allow majority ownership, the maximum amount permitted under such law) or more of the voting equity securities or other equivalent voting interests of the entity.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Software Terms </p>
<p style="text-align:justify;  padding-right: 15px;"><strong>Your License Rights </strong><br>
Subject to the terms and conditions of this Agreement, BRIDGEi2i grants you a non-exclusive, non-sublicense able and non-transferable license to install and use the Software during the applicable License Term in accordance with this Agreement, your applicable Scope of Use, and the Documentation. The term of each Software license ("<b>License Term</b>") will be specified in your Order. Your License Term will end upon any termination of this Agreement, even if it is identified as "perpetual" or if no expiration date is specified in your Order. The Software requires authorization from HP in order to operate, which shall be raised with any new order. <br><br>
<strong>Number of Instances </strong><br>
Unless otherwise specified in your BRIDGEi2i  Order, for each Software license that you purchase, you may install one production instance of the Software on systems owned or operated by you (or your third party service providers so long as you remain responsible for their compliance with the terms and conditions of this Agreement)<br><br>
<strong>Your Modifications </strong><br>
Subject to the terms and conditions of this Agreement (including without limitation Section 2 (Combining the Products with Open Source Software) of Third Party Code in BRIDGEi2i Products): (1) for any elements of the Software provided by BRIDGEi2i in source code form, and to the extent permitted in the Documentation, you may modify such source code solely for purposes of developing bug fixes, customizations and additional features for the Software and (2) you may also modify the Documentation to reflect your permitted modifications of the Software source code or the particular use of the Products within your organization. Any modified source code or Documentation constitutes "<b>Your Modifications</b>". You may use Your Modifications solely with respect to your own instances in support of your permitted use of the Software but you may not distribute the code to Your Modifications to any third party. Notwithstanding anything in this Agreement to the contrary, BRIDGEi2i has no support, warranty, indemnification or other obligation or liability with respect to Your Modifications or their combination, interaction or use with our Products. You shall indemnify, defend and hold us harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including reasonable attorneys' fees and costs) arising out of or in connection with any claim brought against us by a third party relating to Your Modifications (including but not limited to any representations or warranties you make about Your Modifications or the Software) or your breach of this Section 6.3. This indemnification obligation is subject to your receiving (i) prompt written notice of such claim (but in any event notice in sufficient time for you to respond without prejudice); (ii) the exclusive right to control and direct the investigation, defence, or settlement of such claim; and (iii) all reasonably necessary cooperation of BRIDGEi2i at your expense.<br><br>
<strong>Attribution </strong><br>
In any use of the Software, you must include the following attribution to BRIDGEi2i on all user interfaces in the following format: "Powered by BRIDGEi2i," which must in every case include a hyperlink to <a href="http://www.bridgei2i.com" target="_blank">www.bridgei2i.com</a> , and which must be in the same format as delivered in the Software.<br><br>
<strong>Third Party Code </strong><br>
The Software includes code and libraries licensed to us by third parties, including open source software. The Products include components subject to the terms and conditions of "open source" software licenses. To the extent applicable, we will identify open source software included in a Product in or through the Product itself. Some of these licenses require us to provide the open source software to you on the terms of the open source license instead of the terms of the Agreement. In that case, the terms of the open source license will apply, and you will have the rights granted in such licenses to the open source software itself, such as access to source code, right to make modifications, and right to reverse engineer. Notwithstanding the foregoing, if you are using the Products in the form provided to you, in accordance with your permitted Scope of Use, with no distribution of software to third parties, then none of these open source licenses impose any obligations on you beyond what is stated in the Agreement.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;padding: 0 0 14px 0;color: #3393e7;"> Hosted Services Terms </p>
<p style="text-align:justify;  padding-right: 15px;"><strong>Access to Hosted Services </strong><br>
Subject to the terms and conditions of this Agreement, BRIDGEi2i grants you a non-exclusive right to access and use the Hosted Services during the applicable Subscription Term (as defined below) in accordance with this Agreement, your applicable Scope of Use and the Documentation. If BRIDGEi2i offers client software (e.g., a desktop or mobile application) for any Hosted Service, you may use such software solely with the Hosted Service, subject to the terms and conditions of this Agreement. You acknowledge that our Hosted Services are on-line, subscription-based products and that we may make changes to the Hosted Services from time to time.<br><br>
<strong>License Terms and Renewals </strong><br>
Services are provided on a license basis for a set term specified in your Order ("<b>Subscription Term</b>"). Except as otherwise specified in your Purchase Order, all subscriptions will automatically renew for periods equal to your initial Subscription Term (and you will be charged at the then-current rates) unless you cancel your license. If you cancel, your license will terminate at the end of then-current billing cycle, but you will not be entitled to any credits or refunds for amounts accrued or paid prior to such termination.<br><br>
<strong>Credentials </strong><br>
You must ensure that all Authorized Users keep their user IDs and passwords for the HP SKU Planner Services strictly confidential and not share such information with any unauthorized person. User IDs are granted to individual, named persons and may not be shared. You are responsible for any and all actions taken using your accounts and passwords, and you agree to immediately notify BRIDGEi2i of any unauthorized use of which you become aware.<br><br>
<strong>Your Data </strong><br>

"Your Data" means any data, content, code, video, images or other materials of any type that you upload, submit or otherwise transmit to or through Hosted Services in HP Workstation. You will retain all right, title and interest in and to Your Data in the form provided to BRIDGEi2i. Subject to the terms of this Agreement, you hereby grant to BRIDGEi2i a non-exclusive, worldwide, royalty-free right to (a) collect, use, copy, store, transmit, modify and create derivative works of Your Data, in each case solely to the extent necessary to provide the applicable Hosted Service to you and (b) for Hosted Services that enable you to share Your Data or interact with other people, to distribute and publicly perform and display Your Data as you (or your Authorized Users) direct or enable through the Hosted Service. BRIDGEi2i may also access your account or instance in order to respond to your support requests or during scheduled maintenance. <br><br>
<strong>Security </strong><br>
BRIDGEi2i implements security procedures to help protect Your Data from security attacks. However, you understand that use of the Hosted Services necessarily involves transmission of Your Data over networks that are not owned, operated or controlled by us, and we are not responsible for any of Your Data lost, altered, intercepted or stored across such networks. We cannot guarantee that our security procedures will be error-free, that transmissions of Your Data will always be secure or that unauthorized third parties will never be able to defeat our security measures or those of our third party service providers.<br><br>
<strong>Storage Limits </strong><br>
There may be storage limits associated with a particular Hosted Service. Since this implementation in on a HP Workstation, we are not accountable for storage issues. BRIDGEi2i reserves the right to charge for additional storage or overage fees at the rates specified for hosted services. We may impose new, or may modify existing, storage limits for the Hosted Services at any time in our discretion, with or without notice to you.<br><br>
<strong>Responsibility for Your Data </strong><br><br>
<strong>General. </strong>You represent and warrant that: (i) you have obtained all necessary rights, releases and permissions to provide all Your Data to BRIDGEi2i and to grant the rights granted to BRIDGEi2i in this Agreement and (ii) Your Data and its transfer to and use by BRIDGEi2i as authorized by you under this Agreement do not violate any Laws (including without limitation those relating to export control and electronic communications) or rights of any third party, including without limitation any intellectual property rights, rights of privacy, or rights of publicity, and any use, collection and disclosure authorized herein is not inconsistent with the terms of any applicable privacy policies. Other than its security obligations under Section 7.5 (Security), BRIDGEi2i assumes no responsibility or liability for Your Data, and you shall be solely responsible for Your Data and the consequences of using, disclosing, storing, or transmitting it.<br><br>
<strong>Sensitive Data. </strong>You will not submit to the Hosted Services (or use the Hosted Services to collect): (i) any personally identifiable information, except as necessary for the establishment of your BRIDGEi2i HP SKU Planner account; (ii) any patient, medical or other protected health information regulated by HIPAA or any similar federal or state laws, rules or regulations; or (iii) any other information subject to regulation or protection under specific laws such as the Gramm-Leach-Bliley Act (or related rules or regulations) ((i) through (iii), collectively, "<b>Sensitive Data</b>"). You also acknowledge that BRIDGEi2i is not acting as your Business Associate or subcontractor (as such terms are defined and used in HIPAA) and that the Hosted Services are not HIPAA compliant. "<b>HIPAA</b>" means the Health Insurance Portability and Accountability Act, as amended and supplemented. Notwithstanding any other provision to the contrary, BRIDGEi2i has no liability under this Agreement for Sensitive Data.<br><br>
<strong>Indemnity for Your Data. </strong>You will defend, indemnify and hold harmless BRIDGEi2i from and against any loss, cost, liability or damage, including attorneys' fees, for which BRIDGEi2i becomes liable arising from or relating to any claim relating to Your Data, including but not limited to any claim brought by a third party alleging that Your Data, or your use of the Hosted Services in breach of this Agreement, infringes or misappropriates the intellectual property rights of a third party or violates applicable law. This indemnification obligation is subject to your receiving (i) prompt written notice of such claim (but in any event notice in sufficient time for you to respond without prejudice); (ii) the exclusive right to control and direct the investigation, defence, or settlement of such claim; and (iii) all reasonable necessary cooperation of BRIDGEi2i at your expense.<br><br>
<strong>Removals and Suspension </strong><br>
BRIDGEi2i has no obligation to monitor any content uploaded to the Hosted Services or HP Workstation server for installation. Nonetheless, if we deem such action necessary based on your violation of this Agreement or in response to takedown requests that we receive, we may (1) remove Your Data from the Hosted Services. We will generally alert you when we take such action and give you a reasonable opportunity to cure your breach, but if we determine that your actions endanger the operation of the Hosted Service or other users, we may suspend your access immediately without notice. You will continue to be charged for the Hosted Service during any suspension period. We have no liability to you for removing or deleting Your Data from or suspending your access to any Hosted Services as described in this section.<br><br>
<strong>Deletion at End of License Term </strong><br>
We may remove or delete Your Data within a reasonable period of time after the termination of your License Term.<br><br>
<strong>Service-Specific Terms</strong><br>
Some of our Hosted Services may be subject to additional terms specific to that service as set forth in our Service-Specific Terms added below.<br> &nbsp; </p>
<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Support and Maintenance</p>
<p style="text-align:justify;  padding-right: 15px;">BRIDGEi2i will provide the support and maintenance services but not entertain further customizations on agreed version during the SoW sign-up for the Products, during the period for which you have paid the applicable fee. Support and Maintenance is subject to the terms of the BRIDGEi2i Support Policy and will be provided at the support level and during the support term specified in your Order. The BRIDGEi2i Support Policy may be modified by BRIDGEi2i from time to time to reflect process improvements or changing practices. Support and Maintenance for Software includes access to New Releases, if and when available. You may use any New Releases that we provide to you during a valid support term in the same way that you use Software, and New Releases are included in the definition of Software in that case. "<b>New Releases</b>" are bug fixes, patches, major or minor releases, or any other changes, enhancements, or modifications to the Software that we make generally commercially available. We cannot assure you of accessibility or availability of the HP SKU server at all times as it is dependent on HP's infrastructure and does not fall under this project's scope and signed SoW.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Training Services</p>
<p style="text-align:justify;  padding-right: 15px;">We will provide training services purchased in an Order in accordance with the descriptions and conditions for those services set forth in the Order and the accompanying service descriptions or datasheets. BRIDGEi2i shall retain all right, title and interest in and to any materials, deliverables, modifications, derivative works or developments related to any training services we provide ("<b>Training Materials</b>"). Any Training Materials provided to you may be used only in connection with the Products subject to the same use restrictions for the Products. <br> &nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;"> Fees and Payment</p>
<p style="text-align:justify;  padding-right: 15px;">10.1   Fees: <br>
If you have bought our Paid License you will be billed immediately and we require a payment mechanism to be selected as soon as you receive notice of such upgrade. You agree to pay all fees correlative to the Services using one of the payment methods BRIDGEi2i supports. Except as otherwise specified in these Terms of Service or otherwise, (i) fees are quoted and payable in United States dollars <br>
(ii) fees are based on Services purchased, <br>
(iii) payment obligations are non-cancellable as of the applicable due date and fees paid are non-refundable, and <br>
(iv) the subscriptions purchased cannot be decreased during the relevant subscription term. All amounts payable under these Terms of Service will be made without setoff or counterclaim, and without any deduction or withholding.<br><br>
10.2  Invoices and Payment:  <br>
All Service fees will be invoiced in advance and in accordance with the applicable Services opted by you. Fees for ancillary Services will be invoiced as set forth in an applicable Statement of Work ("SOW"). Except as otherwise set forth in the applicable SOW, you agree to pay all invoiced amounts within seven (7) calendar days of the invoice date.<br><br>
10.3  Overdue Charges: <br>
If BRIDGEi2i does not receive fees by the due date, then at BRIDGEi2i's discretion, (i) such charges may accrue late interest at the rate of 1.5% of the outstanding balance per month, or the maximum rate permitted by law, whichever is lower, from the date such payment was due until the date paid; and/or <br>
(ii) BRIDGEi2i may condition future subscription renewals and SOWs on payment terms shorter than those specified in Section 10.2 (Invoices and Payment).<br><br>
10.4  Suspension of Service and Acceleration: <br>
If any amount you owe under these Terms of Service for the Services is 60 or more days overdue, BRIDGEi2i may, without limiting BRIDGEi2's other rights and remedies suspend your access to the Services or use of any application or ancillary services until such amounts are paid in full.<br><br>
10.5  Payment Disputes: <br>
 BRIDGEi2i agrees that it will not exercise its rights under Section 10.4 (Overdue Charges) or 10.5 (Suspension of Service and Acceleration) if the applicable charges are under reasonable and good faith dispute and you are cooperating diligently to resolve the dispute.<br><br>
 10.6 Taxes: <br>
 You are solely responsible for the payment of all taxes, assessments, tariffs, duties or other fees imposed, assessed or collected by or under the authority of any governmental body (collectively, "Taxes") arising from BRIDGEi2i's provision of the Services hereunder, except any taxes assessed upon BRIDGEi2i's net income. If BRIDGEi2i is required to directly pay Taxes related to your use of any Services hereunder, you agree to promptly reimburse BRIDGEi2i for any amounts paid by BRIDGEi2i.<br><br>
 10.7 Prices are subject to change as and when BRIDGEi2i deems fit. All prices listed on the SoW are subject to confirmation. Fees and charges for any new Service or new feature of a Service will be effective when we post updated purchase order. The prices may differ if new work-items have been added to the prior agreed SoW with HP. The products are billed separately during phases.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Restrictions</p>
<p style="text-align:justify;  padding-right: 15px;">Except as otherwise expressly permitted in this Agreement, you will not: (a) rent, lease, reproduce, modify, adapt, create derivative works of, distribute, sell, sublicense, transfer, or provide access to the Products to a third party, (b) use the Products for the benefit of any third party, (c) incorporate any Products into a product or service you provide to a third party, (d) interfere with any license key mechanism in the Products or otherwise circumvent mechanisms in the Products intended to limit your use, (e) reverse engineer, disassemble, decompile, translate, or otherwise seek to obtain or derive the source code, underlying ideas, algorithms, file formats or non-public APIs to any Products, except as permitted by law, (f) remove or obscure any proprietary or other notices contained in any Product, or (g) publicly disseminate information regarding the performance of the Products.<br> &nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">License Certifications and Audits</p>
<p style="text-align:justify;  padding-right: 15px;">At our request, you agree to provide a signed certification that you are using all Products pursuant to the terms of this Agreement, including the Scope of Use. You agree to allow us, or our authorized agent, to audit your use of the Products. We will provide you with at least 10 days advance notice prior to the audit, and the audit will be conducted during normal business hours. We will bear all out-of-pocket costs that we incur for the audit, unless the audit reveals that you have exceeded the Scope of Use. You will provide reasonable assistance, cooperation, and access to relevant information in the course of any audit at your own cost. If you exceed your Scope of Use, we may invoice you for any past or ongoing excessive use, and you will pay the invoice promptly after receipt. This remedy is without prejudice to any other remedies available to BRIDGEi2i at law or equity or under this Agreement. To the extent we are obligated to do so, we may share audit results with certain of our third party licensors or assign the audit rights specified in this Section to such licensors.<br> &nbsp; </p>
<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Ownership and Feedback</p>
<p style="text-align:justify;  padding-right: 15px;">Products are made available on a limited license or access basis, and no ownership right is conveyed to you, irrespective of the use of terms such as "purchase" or "sale". BRIDGEi2i and its licensors have and retain all right, title and interest, including all intellectual property rights, in and to the Products their "look and feel", any and all related or underlying technology, algorithms and any modifications or derivative works of the foregoing created by or for BRIDGEi2i, including without limitation as they may incorporate feedback. From time to time, you may choose to submit comments, information, questions, data, ideas, description of processes, or other information to BRIDGEi2i, including sharing Your Modifications or in the course of receiving Support and Maintenance. BRIDGEi2i may in connection with any of its products or services freely use, copy, disclose, license, distribute and exploit any Feedback in any manner without any obligation, royalty or restriction based on intellectual property rights or otherwise. No Feedback will be considered your Confidential Information, and nothing in this Agreement limits BRIDGEi2i's right to independently use, develop, evaluate, or market products, whether incorporating Feedback or otherwise.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Confidentiality</p>
<p style="text-align:justify;  padding-right: 15px;">Except as otherwise set forth in this Agreement, each party agrees that all code, inventions, know-how, business, technical and financial information disclosed to such party ("<b>Receiving Party</b>") by the disclosing party ("<b>Disclosing Party</b>") constitute the confidential property of the Disclosing Party ("<b>Confidential Information</b>"), provided that it is identified as confidential at the time of disclosure. Any BRIDGEi2i Technology and any performance information relating to the Products shall be deemed Confidential Information of BRIDGEi2i without any marking or further designation. Except as expressly authorized herein, the Receiving Party will hold in confidence and not use or disclose any Confidential Information. The Receiving Party's nondisclosure obligation shall not apply to information which the Receiving Party can document: (i) was rightfully in its possession or known to it prior to receipt of the Confidential Information; (ii) is or has become public knowledge through no fault of the Receiving Party; (iii) is rightfully obtained by the Receiving Party from a third party without breach of any confidentiality obligation; or (iv) is independently developed by employees of the Receiving Party who had no access to such information. The Receiving Party may also disclose Confidential Information if so required pursuant to a regulation, law or court order (but only to the minimum extent required to comply with such regulation or order and with advance notice to the Disclosing Party). The Receiving Party acknowledges that disclosure of Confidential Information would cause substantial harm for which damages alone would not be a sufficient remedy, and therefore that upon any such disclosure by the Receiving Party the Disclosing Party shall be entitled to appropriate equitable relief in addition to whatever other remedies it might have at law. For the avoidance of doubt, this Section shall not operate as a separate warranty with respect to the operation of any Product.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Term and Termination</p>
<p style="text-align:justify;  padding-right: 15px;">This Agreement is in effect for as long as you have a valid License Term, unless sooner terminated as permitted in this Agreement. Either party may terminate this Agreement before the expiration of the Term if the other party materially breaches any of the terms of this Agreement and does not cure the breach within thirty (30) days after written notice of the breach. Either party may also terminate the Agreement before the expiration of the Term if the other party ceases to operate, declares bankruptcy, or becomes insolvent or otherwise unable to meet its financial obligations. You may terminate this Agreement at any time with notice to BRIDGEi2i, but you will not be entitled to any credits or refunds as a result of convenience termination for prepaid but unused Software, Hosted Services subscriptions, servers or Support and Maintenance. Except where an exclusive remedy may be specified in this Agreement, the exercise by either party of any remedy, including termination, will be without prejudice to any other remedies it may have under this Agreement, by law, or otherwise. Once the Agreement terminates, you (and your Authorized Users) will no longer have any right to use or access any Products, or any information or materials that we make available to you under this Agreement, including BRIDGEi2i Confidential Information. You are required to delete any of the foregoing from your systems as applicable (including any third party systems operated on your behalf) and provide written certification to us that you have done so at our request. The following provisions will survive any termination or expiration of this Agreement: Sections 7.7.3 (Indemnity for Your Data), 10 (Fees and Payment), 11 (No-Charge Products) (disclaimers and use restrictions only), 11 (Restrictions), 12 (License Certifications and Audits), 13 (Ownership and Feedback), 14 (Confidentiality), 15 (Term and Termination), 16..2 (Warranty Disclaimer), 19 (Limitation of Liability), 24 (Dispute Resolution), 25 (Export Restrictions), and 27 (General Provisions).<br> &nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;"> Warranty and Disclaimer</p>
<p style="text-align:justify;  padding-right: 15px;"><strong>Due Authority </strong><br> 
Each party represents and warrants that it has the legal power and authority to enter into this Agreement, and that, if you are an entity, this Agreement and each Order is entered into by an employee or agent of such party with all necessary authority to bind such party to the terms and conditions of this Agreement.<br><br>
<strong>WARRANTY DISCLAIMER</strong><br>
ALL PRODUCTS ARE PROVIDED "AS IS," AND BRIDGEI2I EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES AND REPRESENTATIONS OF ANY KIND, INCLUDING ANY WARRANTY OF NON-INFRINGEMENT, TITLE, FITNESS FOR A PARTICULAR PURPOSE, FUNCTIONALITY, OR MERCHANTABILITY, WHETHER EXPRESS, IMPLIED, OR STATUTORY. YOU MAY HAVE OTHER STATUTORY RIGHTS, BUT THE DURATION OF STATUTORILY REQUIRED WARRANTIES, IF ANY, SHALL BE LIMITED TO THE SHORTEST PERIOD PERMITTED BY LAW. BRIDGEI2I SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, SERVICE FAILURES AND OTHER PROBLEMS INHERENT IN USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS OR OTHER SYSTEMS OUTSIDE THE REASONABLE CONTROL OF BRIDGEI2I. TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER BRIDGEI2I NOR ANY OF ITS THIRD PARTY SUPPLIERS MAKES ANY REPRESENTATION, WARRANTY OR GUARANTEE AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, TRUTH, AVAILABILITY, ACCURACY OR COMPLETENESS OF ANY PRODUCTS OR ANY CONTENT THEREIN OR GENERATED THEREWITH, OR THAT: (A) THE USE OF ANY PRODUCTS WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE; (B) THE PRODUCTS WILL OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM, OR DATA; (C) THE PRODUCTS (OR ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE PRODUCTS) WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS); (D) ANY STORED DATA WILL BE ACCURATE OR RELIABLE OR THAT ANY STORED DATA WILL NOT BE LOST OR CORRUPTED; (E) ERRORS OR DEFECTS WILL BE CORRECTED; OR (F) THE PRODUCTS (OR ANY SERVER(S) THAT MAKE A HOSTED SERVICE AVAILABLE) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.<br> &nbsp; </p>
<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Limitation of Liability</p>
<p style="text-align:justify;  padding-right: 15px;">NEITHER PARTY (NOR ITS SUPPLIERS) SHALL BE LIABLE FOR ANY LOSS OF USE, LOST OR INACCURATE DATA, FAILURE OF SECURITY MECHANISMS, INTERRUPTION OF BUSINESS, COSTS OF DELAY OR ANY INDIRECT, SPECIAL, INCIDENTAL, RELIANCE OR CONSEQUENTIAL DAMAGES OF ANY KIND (INCLUDING LOST PROFITS), REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF INFORMED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE. NEITHER PARTY'S AGGREGATE LIABILITY TO THE OTHER SHALL EXCEED THE AMOUNT ACTUALLY PAID BY YOU TO US FOR PRODUCTS AND SUPPORT AND MAINTENANCE IN THE 12 MONTHS IMMEDIATELY PRECEDING THE CLAIM. NOTWITHSTANDING ANYTHING ELSE IN THIS AGREEMENT. THIS SECTION 17 (LIMITATION OF LIABILITY) SHALL NOT APPLY TO (1) AMOUNTS OWED BY YOU UNDER ANY ORDERS, (2) EITHER PARTY'S EXPRESS INDEMNIFICATION OBLIGATIONS IN THIS AGREEMENT, OR (3) YOUR BREACH OF SECTION 11(RESTRICTIONS) OR SECTION 2 (COMBINING THE PRODUCTS WITH OPEN SOURCE SOFTWARE) OF THIRD PARTY CODE IN BRIDGEI2I PRODUCTS). TO THE MAXIMUM EXTENT PERMITTED BY LAW, NO SUPPLIERS OF ANY THIRD PARTY COMPONENTS INCLUDED IN THE PRODUCTS WILL BE LIABLE TO YOU FOR ANY DAMAGES WHATSOEVER. The parties agree that the limitations specified in this Section 19 (Limitation of Liability) will survive and apply even if any limited remedy specified in this Agreement is found to have failed of its essential purpose.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">IP Indemnification by BRIDGEi2i</p>
<p style="text-align:justify;  padding-right: 15px;">We will defend you against any claim brought against you by a third party alleging that a Product, when used as authorized under this Agreement, infringes a United States or European Union patent or registered copyright (a "<b>Claim</b>"), and we will indemnify you and hold you harmless against any damages and costs finally awarded by a court of competent jurisdiction or agreed to settlement by BRIDGEi2i (including reasonable attorneys' fees) arising out of a Claim, provided that we have received from you: (a) prompt written notice of the claim (but in any event notice in sufficient time for us to respond without prejudice); (b) reasonable assistance in the defence and investigation of the claim, including providing us a copy of the claim and all relevant evidence in your possession, custody or control; and (c) the exclusive right to control and direct the investigation, defence, and settlement (if applicable) of the claim. If your use of a Product is (or in our opinion is likely to be) enjoined, if required by settlement, or if we determine such actions are reasonably necessary to avoid material liability, we may, at our option and in our discretion: (i) procure a license for your continued use of the Product in accordance with this Agreement; (ii) substitute a substantially functionally similar Product; or (iii) terminate your right to continue using the Product and refund, in the case of Software, the license fee paid by you as reduced to reflect a three year straight-line depreciation from the license purchase date, and in the case of a Hosted Service, any prepaid amounts for the terminated portion of the Subscription Term. BRIDGEi2i's indemnification obligations above do not apply: (1) if the total aggregate fees received by BRIDGEi2i with respect to your license to Software or subscription to Hosted Services in the 12 month period immediately preceding the claim is less than US$50,000; (2) if the Product is modified by any party other than BRIDGEi2i, but solely to the extent the alleged infringement is caused by such modification; (3) if the Product is used in combination with any non-BRIDGEi2i product, software or equipment, but solely to the extent the alleged infringement is caused by such combination; (4) to unauthorized use of Products; (5) to any Claim arising as a result of (y) Your Data (or circumstances covered by your indemnification obligations in Section 7.7.3 (Indemnity for Your Data)) or (z) any third-party deliverables or components contained with the Products; (6) to any unsupported release of the Software; or (7) if you settle or make any admissions with respect to a claim without BRIDGEi2i's prior written consent. THIS SECTION 18 (IP INDEMNIFICATION BY BRIDGEI2I) STATES OUR SOLE LIABILITY AND YOUR EXCLUSIVE REMEDY FOR ANY INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS IN CONNECTION WITH ANY PRODUCT OR OTHER ITEMS PROVIDED BY BRIDGEI2I UNDER THIS AGREEMENT.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Third Party Vendor Products</p>
<p style="text-align:justify;  padding-right: 15px;">BRIDGEi2i or third parties may from time to time make available to you by embedding them in our code. If you procure any of these third party software or services, you do so under a separate agreement (and exchange of data) solely between you and the third party vendor. BRIDGEi2i does not warrant or support non-BRIDGEi2i products or services, whether or not they are designated by BRIDGEi2i as "verified" or otherwise, and disclaims all liability for such products or services. If you install or enable any third party products or services for use with BRIDGEi2i products, you acknowledge that BRIDGEi2i may allow the vendors of those products and services to access Your Data as required for the interoperation and support of such add-ons with the BRIDGEi2i products. BRIDGEi2i shall not be responsible for any disclosure, modification or deletion of Your Data resulting from any such access by third party add-on vendors.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Publicity Rights</p>
<p style="text-align:justify;  padding-right: 15px;">We may identify you as a BRIDGEi2i customer in our promotional materials. You may request that we stop doing so by submitting an email to <a href="mailto:apps@BRIDGEi2i.com">apps@bridgei2i.com</a> at any time. Please note that it may take us up to 30 days to process your request.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Dispute Resolution; Arbitration</p>
<p style="text-align:justify;  padding-right: 15px;">These Terms of Service and your use of the Website and any Services shall be governed by and construed in accordance with the laws of India. Though we may use hosting services or servers placed outside of India, You agree that any action in Law or in-equity arising out of or relating to these Terms of Service shall be filed only in India and you hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of the courts located in Bangalore, India. In the event of any conflicts between foreign law, rules, and regulations, and Indian law, rules, and regulations, Indian law, rules, and regulations shall prevail and govern.<br><br>
In case any disputes arises dealing with, but not limited to, the interpretation or the enforceability of the Terms of Service, website or the services herein the same shall be submitted for resolution to sole arbitrator, appointed under the Arbitration and Conciliation Act, 1996. The seat of arbitration will be Bangalore and the language of arbitration shall be English. The award of the sole arbitrator shall be final and binding on all parties to the dispute.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Changes to this Agreement</p>
<p style="text-align:justify;  padding-right: 15px;">We may update or modify this Agreement from time to time, including any referenced policies and other documents. If a revision meaningfully reduces your rights, we will use reasonable efforts to notify you (by, for example, sending an email to the billing or technical contact you designate in the applicable Order, posting on our blog, through your BRIDGEi2i account, or in the Product itself). If we modify the Agreement during your License Term or Subscription Term, the modified version will be effective upon your next renewal of a License Term, Support and Maintenance term, or Subscription Term, as applicable. In this case, if you object to the updated Agreement, as your exclusive remedy, you may choose not to renew, including cancelling any terms set to auto-renew. With respect to No-Charge Products, accepting the updated Agreement is required for you to continue using the No-Charge Products. You may be required to click through the updated Agreement to show your acceptance. If you do not agree to the updated Agreement after it becomes effective, you will no longer have a right to use No-Charge Products. For the avoidance of doubt, any Order is subject to the version of the Agreement in effect at the time of the Order.<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Notices and Communication</p>
<p style="text-align:justify;  padding-right: 15px;">BRIDGEi2i communicates with you through the email address you have provided us. It is your responsibility to keep your email address and snail mail address updated at all times. You consent to receive communications from us electronically and you agree that these electronic communications satisfy any legal requirement that such communications be in writing. If you fail to respond to an email message regarding violation, dispute or complaint within two business days, we reserve the right to terminate or suspend your access and use of the Services.<br><br>
All notices to us intended to have a legal effect must be in writing and delivered to the following address:<br><br>
Umiya Business Bay, Tower 1, 2nd Floor Cessna Business Park, Village, Vartur Hobli, Outer Ring Rd, Kadubeesanahalli, Bengaluru, Karnataka 560037<br> &nbsp; </p>

<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;"> Severability</p>
<p style="text-align:justify;  padding-right: 15px;">If any provision of these Terms of Service shall be deemed unlawful, void or for any reason unenforceable by a competent court, then that provision shall be deemed severable from these Terms of Service and shall not affect the validity and enforceability of any remaining provisions.<br>
&nbsp; </p>


<p style="border-bottom: 1px solid #e8e8e8; margin: 0 0 10px 0;font-size: 22px;line-height: 25px;font-weight: 500;padding: 0 0 14px 0;color: #3393e7;">Contact Information </p> 
<p style="text-align:justify;  padding-right: 15px;">Questions or comments about the Website or the Services may be directed to BRIDGEi2i at the email address <a href="mailto:apps@BRIDGEi2i.com">apps@bridgei2i.com</a> <br> &nbsp; </p>


					</div>
					
					
				</div>
			</div>


		</div>
	</form:form>

</body>
</html>